site_name: Social Scope
site_description: SocialScope harnesses the power of data science to Instagram's vast content, providing insightful analytics and trend predictions for informed decision-making.

repo_url: https://github.com/r-a-j/Social-Scope
repo_name: r-a-j/Social-Scope
edit_uri: edit/main/docs/docs
copyright: Project maintained by <a target=_blanks href="https://rajpawar.in">Raju</a> &#128568;

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      fallback_to_build_date: true
  - git-committers:
      enabled: true
      repository: r-a-j/Social-Scope
      branch: main

theme:
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  logo: assets/logo.png    
  favicon: favicon.ico
  language: en
  name: material
  features:
    - navigation.sections  
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.follow
    - header.autohide
    - navigation.footer
    - content.action.view
    - content.action.edit
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - css/extra.css

markdown_extensions:
  - tables
  - md_in_html
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
  - pymdownx.superfences

extra:
  consent:
    actions:
      - accept
      - manage
      - reject
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.    
  analytics:
    provider: google
    property: G-9NMXFC18QL

nav:
  - Home: index.md
  - Development Docs: development-docs.md
  - Scraper: scraper.md
  - Sentiment Analysis: sentiment-analysis.md
  - Image Recognition: image-recognition.md
  - Content Trend Analysis: content-trend-analysis.md
  - User Engagement Prediction: user-engagement-prediction.md
  - Community Detection: community-detection.md
  - Hashtag Analysis: hashtag-analysis.md
  - Influencer Identification: influencer-identification.md
  - Recommender Systems: recommender-systems.md
  - Time Series Analysis: time-series-analysis.md
  - Network Analysis: network-analysis.md